### ISSUE TITLE
Compiler error from Stainless library on OSX 10.12.6

### ISSUE THREAD

**Issue by vanthemilton** [reem/stainless#85]
```Attempting to use Stainless for integration testing. Rust compiler complains:

Compiling stainless v0.1.11
error[E0063]: missing field `tokens` in initializer of `syntax::ast::Item`
   --> /Users/jimdandy/.cargo/registry/src/github.com-1ecc6299db9ec823/stainless-0.1.11/src/generate.rs:113:11
    |
113 |         P(ast::Item {
    |           ^^^^^^^^^ missing `tokens`

error[E0063]: missing field `tokens` in initializer of `syntax::ast::Item`
   --> /Users/jimdandy/.cargo/registry/src/github.com-1ecc6299db9ec823/stainless-0.1.11/src/generate.rs:149:11
    |
149 |         P(ast::Item {
    |           ^^^^^^^^^ missing `tokens`

error: aborting due to 2 previous errors

error: Could not compile `stainless`.
```

**Comment by Howardlinsanity** [comment]
I'm working with vanthemilton, and another detail is that we're running on the nightly toolchain, rustc 1.21.0-nightly.

**Comment by cjppku** [comment]
Met the same problem to compile stainless, both in windows & in MacOSX. Please fix it, thanks. 
```
error[E0063]: missing field `tokens` in initializer of `syntax::ast::Item`
   --> /Users/jchen/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/stainless-0.1.11/src/generate.rs:113:11
    |
113 |         P(ast::Item {
    |           ^^^^^^^^^ missing `tokens`
error[E0063]: missing field `tokens` in initializer of `syntax::ast::Item`
   --> /Users/jchen/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/stainless-0.1.11/src/generate.rs:149:11
    |
149 |         P(ast::Item {
    |           ^^^^^^^^^ missing `tokens`

   Compiling num-bigint v0.1.40
error: aborting due to 2 previous errors
```

**Comment by cjppku** [comment]
It works on nightly-1.20.0, but report error on nightly-1.21.0

**Comment by neverfox** [comment]
Same on `rustc 1.21.0-nightly (ab40a7cb0 2017-08-13)`.
